name: ci-pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: npm run build

      - name: Run ESLint
        run: npm run lint

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: marketplace-frontend
          path: |
            dist
            nginx.conf
            
  test:
    if: false
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Download build output
      uses: actions/download-artifact@v4
      with:
        name: marketplace-frontend
        path: dist

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/

  sonarqube:
    # needs: test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish:
    needs: sonarqube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: marketplace-frontend
          path: dist

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
    
      - name: Docker login
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: bryrmiginte
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: ./dist
          file: Dockerfile
          push: true
          tags: bryrmiginte/marketplace-frontend:latest
